services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - ./.env
    container_name: nextjs-app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./data:/app/data
