name: Dashboard Admin Gnawalma on dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy-on-dev:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repos
        uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          password: ${{ secrets.PASSWORD_DEV }}
          source: "."
          target: $HOME/front_gnawalma
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          password: ${{ secrets.PASSWORD_DEV }}
          script: |
            cd $HOME/front_gnawalma
            docker compose up --build --force-recreate -d
            docker system prune -f
